name: Sync Live M3U

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

# 核心修改：明确声明给这个脚本写入代码仓库的权限
permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download M3U File
        run: |
          curl -k --retry 3 --retry-delay 5 -o kl_lives.m3u "http://Live.445569.xyz/live.m3u"
          
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add kl_lives.m3u
          git commit -m "Auto sync kl_lives.m3u" || exit 0
          git push
